var width = 800
var height= 500

var svg =  d3.select("#teamsuccess_viz1")
  .style("width", width)
  .style("height", height)

var title = svg.append("text") 
              .text('Team Success') 
              .attr("text-anchor", "middle") 
              .style("font-size", '24px') 
              .attr("dy", 20)
              .attr("dx", width / 2);

let border = svg.append("g")
                .append("rect")
                .attr("stroke-width", 2)
                .attr("stroke", "black")
                .attr("fill", "none")
                .attr("y", 25)
                .attr("width", width)
                .attr("height", height-25)

var temp_holder = svg.append("text")
                    .text('<Visualization 1>')
                    .attr("text-anchor", "middle")
                    .style("font-size", "12px")
                    .attr("dx", border.attr("width")/2)
                    .attr("dy", border.attr("height")/2)

console.log(border.attr("width"))

  /*
let bound = svg.append("g")
            .attr("transform", `translate(10,0)`)

let link = bound.insert("g")
            .attr("fill", "none")
            .attr("stroke", "#555")
            .attr("stroke-opacity", 0.4)
            .attr("stroke-width", 2)
            .selectAll("path")
            .data(root.links()) //TODO: here you have to pass the links generated by your hierarchy
            .join("path")
            .attr("d", d3.linkHorizontal()
                  .x(d => d.y)
                  .y(d => d.x));


console.log(root.descendants());


const node = bound.append("g")
            .selectAll("circle")
            .data(root.descendants()) //TODO: here you have to pass the descendants of your root
            .enter()
            .append("circle")
            .attr("transform", d => `translate(${d.y},${d.x})`)
            .attr("fill", d => d.children ? "#555" : "#999")
            .attr("r", 4)
*/